# Generated by Django 6.0.4 on 2026-06-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_detalle_ticket_codigo_barras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_ticket',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
